import React, { useState } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { FORM_DATA } from '../../constants';
import nstar from '../../assets/images/nstar.png';
import pps1350 from '../../assets/images/pps1350.png';
import hermes from '../../assets/images/hermes.png';
import { motion } from 'framer-motion';
import { Icon } from '@chakra-ui/core';
import ModalMotor from './ModalMotor';

const motors = [
  {
    name: 'NSTAR',
    description:
      'The NASA Solar Technology Application Readiness (NSTAR) is a type of spacecraft ion thruster called electrostatic ion thruster. It is a highly efficient low-thrust spacecraft propulsion running on electrical power generated by solar arrays. It uses high-voltage electrodes to accelerate ions with electrostatic forces.',
    specificImpulse: 2600,
    specificImpulseUnits: 's',
    maxThrust: 586,
    maxThrustUnits: 'mN',
    image: nstar
  },
  {
    name: 'PPS-1350',
    description:
      'PPS-1350 is a Hall-effect thruster, a kind of ion propulsion system for spacecraft. It was used in the SMART-1 mission to the moon and two geostationary satellites: Inmarsat-4A F4 and Hispasat AG1.',
    specificImpulse: 2600,
    specificImpulseUnits: 's',
    maxThrust: 586,
    maxThrustUnits: 'mN',
    image: pps1350
  },
  {
    name: 'HERMeS',
    description:
      'The NASA Hall Effect Rocket with Magnetic Shielding (HERMeS) 12.5 kW Technology Demons-tration Unit-1 (TDU-1) Hall thruster has been the subject of extensive technology maturation in preparation for development into a flight ready propulsion system.',
    specificImpulse: 2600,
    specificImpulseUnits: 's',
    maxThrust: 586,
    maxThrustUnits: 'mN',
    image: hermes
  }
];

const MotorElectric = (props) => {
  const dispatch = useDispatch();
  const data = useSelector((state) => state.moltoItConfig);
  const [currentMotor, setCurrentMotor] = useState({
    name: data.motor,
    description: '',
    specificImpulse: data.specificImpulse,
    specificImpulseUnits: data.specificImpulseUnits,
    maxThrust: '0',
    maxThrustUnits: 'mN',
    image: ''
  });
  const [modalInfo, setModalInfo] = useState(false);

  console.log(modalInfo);
  const handleClick = (motor) => {
    setCurrentMotor(motor);
    dispatch({ type: FORM_DATA, payload: { Isp: motor.specificImpulse } });
    dispatch({ type: FORM_DATA, payload: { nthrusters: 1 } });
    dispatch({ type: FORM_DATA, payload: { motor: motor.name } });
    dispatch({ type: FORM_DATA, payload: { motorType: 'Electric' } });
  };
  const isClose = () => {
    setModalInfo(false);
  };
  console.log(currentMotor);
  return (
    <div className="motor__container__electric">
      {motors.map((motor_) => (
        <motion.div
          whileHover={{ scale: 1.1 }}
          className="motor__option"
          onClick={() => handleClick(motor_)}
        >
          {currentMotor.name === motor_.name ? (
            <div className="container__check">
              <Icon name="check-circle" size="30px" color="green.400" />
            </div>
          ) : null}

          <p className="TitleMotor"> {motor_.name}</p>

          <img
            src={motor_.image}
            style={{
              width: motor_.name === 'NSTAR' ? '50%' : '60%',
              height: motor_.name === 'NSTAR' ? '50%' : '60%',
              marginTop: '10px'
            }}
            alt="motors"
          />

          <motion.div
            whileHover={{
              scale: 1.05,
              backgroundColor: 'rgba(255,255,255,0.3)'
            }}
            onClick={() => setModalInfo(true)}
            className="mission__button"
          >
            Information
          </motion.div>
        </motion.div>
      ))}
      {modalInfo ? (
        <ModalMotor isClose={isClose} open={true} motor={currentMotor} />
      ) : null}
    </div>
  );
};

export default MotorElectric;
